### ISSUE TITLE
Status indicator 'Import objects'

### ISSUE THREAD

**Issue by fvet** [NAVBaaS/GitIntegration#10]
Would it be possible to provide some kind of status / progress indicator about the 'Import Objects' stage? When initializing a new container for the first time, it takes long (30+ minutes) to import our objects and some might think the process is frozen.
```
VERBOSE: No commit hash found for container W1DEV - importing all objects from c:\users\fvet\modified
VERBOSE: 0 objects to delete.
VERBOSE: 5900 objects to import.
VERBOSE: 0 objects to export.
VERBOSE: Creating text file to import.
VERBOSE: **Importing objects.**
```
One alternative option might be to split the import in stages per object type (tables / pages / ...)?

Any other ideas on how to improve the speed of creating a new container? If we have a bak file that was recently created at a certain commit, I guess manually setting the LastCommitHash would speed up the sync command?

**Comment by richardrobberse** [comment]
Progress bar is unfortunately not possible and there's no way to improve the performance, parallel importing causes locks on the object table.

The only thing I could do is to import in batches to provide a little bit of progress, that'll probably be a lot of code for something which is not really necessary.

Manually setting the right commit hash is indeed the way to go if you provide a bak file, would it help if I add an input box to the create container command so that you can set it directly?

**Comment by fvet** [comment]
LastCommitHash does the trick.  It would be nice integrating it in the 'Create Container' command as an extra option.
