### ISSUE TITLE
Use relative paths from Workspace settings?

### ISSUE THREAD

**Issue by fvet** [NAVBaaS/GitIntegration#15]
Instead of managing my scripts / license files on a share, I'd like to include those in the GIT repository, on a separate 'Resources' folder. Relative links to these paths will then be added to the 'Workspace' settings in VSCode.

```
    "NAVBaaS.OnBeforeCreateContainerScriptPath": "/Resources/Scripts/OnBeforeCreateContainer.ps1",
    "NAVBaaS.LicenseFile": "/Resources/License/NAV2018.flf"    
```

However, seems like the 'NAVBaaS : Create container' fails on using these files? 

`Could not find license file /Resources/...`

**Comment by richardrobberse** [comment]
Correct, the settings are not interpreted as relative paths because I expected people to not store them in git.

Is it a problem to specify the full path?
Otherwise I have to figure out whether the path exists and if not, join it with the path of the repository.

It's definitely possible to do so but it might be not so clear to others.

**Comment by richardrobberse** [comment]
For now, just specify the full path and remember that the user settings is in json format so you need to specify two backslashes instead of one when defining paths.

I'm thinking of accepting URLs for settings that are currently file path based and I'll handle that in the other issue you've reported.
