### ISSUE TITLE
Support for Azure Container Instances?

### ISSUE THREAD

**Issue by fvet** [NAVBaaS/GitIntegration#17]
The NAVBaaS extension seems a viable candidate for our _Product_ development team, which only needs a limited no. of containers to be available (locally). However, for our _Project_ development team, we're considering moving towards Azure container instances (to allow more containers to be active simultanuously - which is a must, improve speed, use Windows Server 2016, ...)

https://azure.microsoft.com/en-us/resources/templates/101-aci-dynamicsnav/

Are there any plans to extend the NAVBaaS extension to support Azure Container service integration?

**Comment by richardrobberse** [comment]
It would indeed be a nice addition, but I'm depending on the navcontainerhelper for this one since I don't want to reinvent the wheel (I know that Microsoft is working on ACI support for the navcontainerhelper)

 I'm in Denmark next week for the ReadyToGo program and I think we have a meeting scheduled with Freddy so I'll bring this one up.

Deploying an ACI is not so hard, I think the real challenge is to work with C/SIDE on a host against the ACI and get the NAV PowerShell cmdlets to work.

I'll keep you posted.

**Comment by richardrobberse** [comment]
Update:
ACI won't be supported by the navcontainerhelper neither by the NAVBaaS Git extension for now because of the following reasons:
- For every ACI you create the entire Docker image needs to be downloaded, this takes too long.
- ACI's are a lot more expensive than virtual machines.
- Interacting with the ACI is a lot more difficult than interacting with a local container, for example if you want to import objects you need to somehow copy the files to the ACI first and then trigger the import on the ACI.
From what I've heard it's not possible to use remote powershell against the ACI.
