### ISSUE TITLE
Creation of new container doesn't seem to update host file

### ISSUE THREAD

**Issue by nickrobbo** [NAVBaaS/GitIntegration#22]
Does the "Create Container" command use the "-updateHosts" switch by default?
I have tried creating multiple containers, and the resulting container is never accessible by the host name, and is only accessible by the IP address.

The strange thing is if I use the New-NAVContainer function directly, it works as expected.  I am not sure if there is a missing switch in the script run by your extension?

I have tested this on two machines, both running Windows 10, Version 1903, (OS Build 18362.295).

**Comment by richardrobberse** [comment]
It does not use the -updateHosts switch by default.
I agree that it's better to use the -updateHosts switch for every container because it seems to be necessary since 1903.
Before 1903, the name resolution worked like a charm (in most cases and when not in a company network) without -updateHosts.

As a workaround, you can create a script with a certain name (the way of doing this is described in the readme of the extension) where you can add additional parameters that are sent to the New-NavContainer function.

**Comment by nickrobbo** [comment]
I have tried to run the following in a script using the "OnBeforeCreateContainer" trigger -
 
`$AdditionalParameters += "--env -updateHosts" `

Am I doing this incorrectly?  As this doesn't seem to work either....
Do you plan to make -updateHosts default in an updated version?

**Comment by richardrobberse** [comment]
My bad, it won't work because the -updateHosts switch is directly used in the New-NavContainer function, adding environment variables will only work if the variables are used in the scripts that are called by 'docker run' (which New-NavContainer does under the hood)

I can release a new version which includes -updateHosts somewhere tonight.

**Comment by nickrobbo** [comment]
Yeah I thought that might be the case, thanks for getting back to me so quickly.

**Comment by richardrobberse** [comment]
No problem, I'll let you know once the update is there.

**Comment by richardrobberse** [comment]
Fixed in version 1.6.12, please give it another try.
