### ISSUE TITLE
Git branches support

### ISSUE THREAD

**Issue by mkilinskidev** [NAVBaaS/GitIntegration#24]
Hi there! I am wondering if is possible to add the git branches support. Probably, after git checkout we shlould make a container synchronization, but how can we do that automaticly?

**Comment by richardrobberse** [comment]
Hi, thanks for using NAVBaaS!

The git commands in VS Code basically call the git CLI so there's no way to hook into that and figure out if the call is relevant.
The only workaround I see is to create my own `git checkout` that automatically synchronizes the container but I doubt if you'd always want to sync your container after a checkout, this could possibly harm the state of your database.

I think it is better to keep this as a manual action so that you're completely in control and no magic will happen. (I do understand there's a big chance of forgetting to sync the container and just continue work)

**Comment by mkilinskidev** [comment]
Ok thanks. I'll check above manually
