### ISSUE TITLE
Invalid database Collation

### ISSUE THREAD

**Issue by mkilinskidev** [NAVBaaS/GitIntegration#25]
Hi there. I've created the docker container with my own database. I am living in Poland so my DB Collation is Polish_100_CS_AS. Now, when I am trying to synchronize container, there is an error:

```
VERBOSE: Importing exported objects.
: [6146889] There is no system code page on your computer that matches the 1250 code page of the Polish_100_CS_AS colla
tion for the mydatabase database.
Your system code pages are: ANSI: 65001, OEM: 65001.
Ensure that the Regional Options of the computer use the correct system language and locale for the code pages to match
.
You can also disable the 'Validate Collation' setting for this database. It is possible that certain text data will not
 be converted correctly when stored in the database.
Click OK to disable the 'Validate Collation' setting and continue to use the database, or click Cancel to exit.
At C:\Users\mkilinski\.vscode\extensions\navbaas.git-1.6.12\ps\m\NavHelper.psm1:286 char:5
+     Invoke-Command -Session $Session -ScriptBlock {
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-NAVApplicationObject
    + PSComputerName        : 55d4285a42128473d5e1d11e0d23afca3a8daf657f42a5d57cad9e08699d3331
 
Finished function: Synchronize container.
```
Is it possible to fix it or inject the Validate Collation parameter?

**Comment by richardrobberse** [comment]
Hi, please have a look at [this issue for the navcontainerhelper](https://github.com/microsoft/navcontainerhelper/issues/781#issuecomment-564440735)
It seems it has to do with ltsc2019 images in combination with Hyper-V isolation.
If possible, use process isolation by using an image that matches with your host OS.

It'll be hard to disable the 'Validate Collation' setting because the parameter is not part of the Docker scripts provided by Microsoft, it's a setting on the SQL database.
Next to that, I think that disabling the validation might introduce other errors, not sure though.

If this is something you want to do I'd suggest creating your own script that runs after the container has been created. Please refer to 'Adding functionality yourself' section in the NAVBaaS extension's 'details' page in VS Code. You can run a custom PowerShell script by specifying the `OnAfterCreateContainerScriptPath` in your VS Code's user settings.

**Comment by mkilinskidev** [comment]
>If possible, use process isolation by using an image that matches with your host OS.

Could you tell me, how can I use it? My host OS is Windows 10 2004. How can I change the ltsc2019 image to ltsc2016 f.ex.?

**Comment by richardrobberse** [comment]
You can specify the ltsc image like this:
mcr.microsoft.com/businesscentral/sandbox:w1-ltsc2019

**Comment by mkilinskidev** [comment]
Gosh... I can't create a container with ltsc2016 version :( 

```
Creating container wenglorz from image microsoft/dynamics-nav:2016-cu9-w1-ltsc2016
4aeb0bb36f5da6cc8f5a35071b6ad750fadeb13457ff6fd239167ae5b57155cc
DockerDo : docker.exe: Error response from daemon: hcsshim::CreateComputeSystem 4aeb0bb36f5da6cc8f5a35071b6ad750fadeb13
457ff6fd239167ae5b57155cc: Operation Timeout
```
But on ltsc2019 it is ok...

UPDATE
I've successfully created the NAV Container with own database and -useBestContainerOs flag :)
