### ISSUE TITLE
Use external database

### ISSUE THREAD

**Issue by fvet** [NAVBaaS/GitIntegration#5]
Just tried to create a container using my own bak file, but it failed due to the SQL Server version conflict (see https://github.com/Microsoft/nav-docker/issues/232) Instead of using a bak file in the NAV container, I'd need to provide access to a SQL database, **external to the container**. Is it possible to provide an extra option in the 'Create Container' command (or in the user / workspace settings) to add the connection parameters for the external SQL (server / instance / databases / credentials)?

Or should I find a way using the OnBeforeCreateContainerScriptPath settings?

**Comment by richardrobberse** [comment]
In the OnBeforeCreateContainerScriptPath you have access to the $AdditionalParams and $AdditionalParameters, the former is prefilled with the parameters I define in the script, you could extend/change those so that it uses external SQL.
However, I'm not sure if this will work, haven't tried this before...

I guess the only reason you want to use external SQL is because you have a database on a higher SQL version and you want the data, right?
You could consider exporting the data (Export-NAVData) -> Create a standard container -> Import objects -> Import-NAVData
Then you're compatible with the NAV Docker images again, which makes your life a lot easier :)

It could also be an option to create the container with your own script, and add it to your user settings in VS Code.
There are a few things that you should take into account when creating the container, for example, a certain shared folder is required to let the container work with the VS Code extension.
Please let me know if you're opting for this one.

Aren't we colleagues anymore?

**Comment by richardrobberse** [comment]
Closed because of no response.
